Use linux-arm64-lts with older glibc for compatibility
This will ensure the prebuild is recognized on more platforms, avoiding
issues like:

    Error: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found
    (required by /home/node/app/prebuilds/linux-arm64/node.napi.armv8.node)

...which prevent the prebuild from being recognized.